import { z } from "zod";
import { publicProcedure, router } from "./_core/trpc";
import { ENV } from "./_core/env";
import { GoogleGenerativeAI } from "@google/generative-ai";

// ── 圖片類型與風格定義 ──────────────────────────────────────────────────────

const IMAGE_TYPE_PROMPTS: Record<string, string> = {
  social_post:
    "square format 1:1 ratio, social media post background, vibrant food photography composition",
  story:
    "vertical format 9:16 ratio, Instagram story background, immersive atmosphere",
  poster:
    "poster layout background, event promotional visual, dramatic lighting",
  product:
    "product photography background, food styling, clean composition, restaurant ambiance",
};

const STYLE_PROMPTS: Record<string, string> = {
  fresh_natural:
    "fresh natural style, soft daylight, green herbs, clean white surfaces, minimalist, airy",
  street_cool:
    "street food culture, urban grunge, neon accents, bold colors, dynamic energy, youth culture",
  literary:
    "literary aesthetic, warm tones, vintage texture, soft bokeh, artisan feel, moody atmosphere",
  vibrant:
    "vibrant colorful, festive energy, bright saturated colors, joyful atmosphere, lively",
};

// ── Imagen 3 圖片生成（透過 Gemini API）────────────────────────────────────

async function generateWithImagen(prompt: string): Promise<string> {
  // Imagen 3 via Google AI SDK
  const client = new GoogleGenerativeAI(ENV.geminiApiKey);
  const model = client.getGenerativeModel({ model: "imagen-3.0-generate-002" });

  // @ts-ignore - imagen API
  const result = await model.generateImages({
    prompt,
    number_of_images: 1,
    aspect_ratio: "1:1",
    safety_filter_level: "block_some",
    person_generation: "dont_allow",
  });

  // @ts-ignore
  const imageData = result.generatedImages?.[0]?.image?.imageBytes;
  if (!imageData) throw new Error("No image generated by Imagen");

  return `data:image/png;base64,${imageData}`;
}

// ── Gemini 2.0 Flash 圖片生成（fallback）──────────────────────────────────

async function generateWithGeminiFallback(prompt: string): Promise<string> {
  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-preview-image-generation:generateContent?key=${ENV.geminiApiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: prompt }],
          },
        ],
        generationConfig: {
          responseModalities: ["IMAGE", "TEXT"],
        },
      }),
    }
  );

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Gemini image generation failed: ${err}`);
  }

  const data = await response.json() as {
    candidates?: Array<{
      content?: {
        parts?: Array<{
          inlineData?: { mimeType: string; data: string };
          text?: string;
        }>;
      };
    }>;
  };

  const parts = data.candidates?.[0]?.content?.parts ?? [];
  const imagePart = parts.find((p) => p.inlineData?.data);
  if (!imagePart?.inlineData) throw new Error("No image in Gemini response");

  const { mimeType, data: imageData } = imagePart.inlineData;
  return `data:${mimeType};base64,${imageData}`;
}

// ── 建構圖片生成 Prompt ────────────────────────────────────────────────────

function buildImagePrompt(
  imageType: string,
  style: string,
  subject: string
): string {
  const typePrompt = IMAGE_TYPE_PROMPTS[imageType] ?? IMAGE_TYPE_PROMPTS.social_post;
  const stylePrompt = STYLE_PROMPTS[style] ?? STYLE_PROMPTS.vibrant;

  return [
    // 核心主題
    subject,
    // 類型構圖
    typePrompt,
    // 風格
    stylePrompt,
    // 酸菜魚餐廳視覺元素
    "Sichuan cuisine restaurant, sour fish hot pot, Chinese food culture, sichuan peppercorns, pickled vegetables, fresh fish, steam rising from bowl",
    // 品質要求
    "high quality, professional food photography, 4K, detailed textures, no text, no words, no letters, no watermark, no logo",
    // 負面提示（避免文字）
    "absolutely no text, no writing, no characters, no symbols, no numbers, no labels",
  ].join(", ");
}

// ── tRPC Router ────────────────────────────────────────────────────────────

export const imageGenRouter = router({
  generateBackground: publicProcedure
    .input(
      z.object({
        imageType: z.enum(["social_post", "story", "poster", "product"]),
        style: z.enum(["fresh_natural", "street_cool", "literary", "vibrant"]),
        subject: z.string().max(200).default("sichuan sour fish hot pot dish"),
      })
    )
    .mutation(async ({ input }) => {
      const prompt = buildImagePrompt(input.imageType, input.style, input.subject);

      let imageBase64: string;
      let usedModel: "imagen3" | "gemini_fallback";

      // 先嘗試 Imagen 3
      try {
        imageBase64 = await generateWithImagen(prompt);
        usedModel = "imagen3";
      } catch (imagenError) {
        console.warn("[ImageGen] Imagen 3 failed, falling back to Gemini:", imagenError);
        // Fallback 到 Gemini 2.0 Flash 圖片生成
        try {
          imageBase64 = await generateWithGeminiFallback(prompt);
          usedModel = "gemini_fallback";
        } catch (geminiError) {
          console.error("[ImageGen] Both Imagen and Gemini failed:", geminiError);
          throw new Error("圖片生成失敗，請稍後再試");
        }
      }

      return {
        imageBase64,
        usedModel,
        prompt,
      };
    }),
});
